# Generated by Django 5.2.17 on 2026-08-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('nic', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('sixty_fifth_birthday', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('firearm_number', models.CharField(max_length=100, unique=True)),
                ('first_licensed_year', models.IntegerField()),
                ('renewal_year', models.IntegerField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('renewal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('renewal_remarks', models.TextField(blank=True, null=True)),
                ('non_renewal_information', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(default='active', max_length=50)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('status_remarks', models.TextField(blank=True, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('previous_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('new_holder_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_details', models.TextField(blank=True, null=True)),
                ('special_information', models.TextField(blank=True, null=True)),
                ('outside_area_holder', models.BooleanField(default=False)),
                ('outside_residential_address', models.TextField(blank=True, null=True)),
                ('land_location_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('firearm_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.firearmtype')),
                ('gn_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.gndivision')),
            ],
        ),
    ]
