# Generated by Django 5.2.17 on 2026-08-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
