# Generated by Django 5.2.17 on 2026-08-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_licenserecord_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserecord',
            name='renewal_history',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
