# Generated by Django 5.2.17 on 2026-08-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_licenserecord_renewal_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserecord',
            name='renewal_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
