# Generated by Django 5.2.17 on 2026-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_licenserecord_renewal_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenserecord',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='licenserecord',
            name='new_holder_reference',
        ),
        migrations.RemoveField(
            model_name='licenserecord',
            name='previous_holder',
        ),
        migrations.RemoveField(
            model_name='licenserecord',
            name='status_date',
        ),
        migrations.RemoveField(
            model_name='licenserecord',
            name='status_remarks',
        ),
        migrations.RemoveField(
            model_name='licenserecord',
            name='transfer_date',
        ),
        migrations.RemoveField(
            model_name='licenserecord',
            name='transfer_details',
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='current_status_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
