# Generated by Django 5.2.17 on 2026-08-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_licenserecord_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserecord',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
