# Generated by Django 5.1.1

from django.db import migrations
from datetime import timedelta

def update_birthday_70(apps, schema_editor):
    LicenseRecord = apps.get_model('records', 'LicenseRecord')
    for record in LicenseRecord.objects.all():
        if record.date_of_birth:
            # We must handle leap years correctly
            try:
                record.sixty_fifth_birthday = record.date_of_birth.replace(year=record.date_of_birth.year + 70)
            except ValueError:
                # Handle Feb 29 leap year issues if any
                record.sixty_fifth_birthday = record.date_of_birth + timedelta(days=70*365 + 17)
            record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_licenserecord_custom_data'),
    ]

    operations = [
        migrations.RunPython(update_birthday_70),
    ]
