# Generated by Django 5.2.17 on 2026-08-16 09:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firearms', '0001_initial'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=datetime.date.today)),
                ('new_holder_reference', models.CharField(help_text='New Holder / Official Reference', max_length=255)),
                ('transfer_details', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('supporting_document_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firearm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='firearms.firearm')),
                ('previous_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='licenses.licenseholder')),
            ],
        ),
    ]
