# Generated by Django 5.2.17 on 2026-08-16 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('License', 'License Document'), ('Renewal', 'Renewal Document'), ('Transfer', 'Transfer Document'), ('Other', 'Other Official Document')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='official_documents/')),
                ('related_license_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='licenses.licenseholder')),
            ],
        ),
    ]
