# Generated by Django 5.2.17 on 2026-08-16 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firearms', '0001_initial'),
        ('licenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonRenewalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('reason_details', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_renewals', to='licenses.licenseholder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_year', models.IntegerField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('renewal_status', models.CharField(choices=[('Active', 'Active'), ('Renewed', 'Renewed'), ('Pending', 'Pending'), ('Not Renewed', 'Not Renewed'), ('Transferred', 'Transferred'), ('Other', 'Other')], default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firearm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='firearms.firearm')),
                ('license_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='licenses.licenseholder')),
            ],
        ),
    ]
