# Generated by Django 5.2.17 on 2026-08-16 09:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='holder_photos/')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('nic', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('telephone_number', models.CharField(max_length=20)),
                ('outside_area_holder', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gn_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_holders', to='core.gndivision')),
            ],
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('status_date', models.DateField(default=datetime.date.today)),
                ('details', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('license_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='licenses.licenseholder')),
            ],
        ),
    ]
