# Generated by Django 5.2.17 on 2026-08-16 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firearm_number', models.CharField(max_length=100, unique=True)),
                ('first_licensed_year', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firearm_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.firearmtype')),
                ('license_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firearms', to='licenses.licenseholder')),
            ],
        ),
    ]
