# Generated by Django 5.2.17 on 2026-08-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_firearmtype_id_alter_gndivision_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_si', models.CharField(max_length=255, verbose_name='Section Title (Sinhala)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Section Title (English)')),
                ('title_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Section Title (Tamil)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label_si', models.CharField(max_length=255, verbose_name='Label (Sinhala)')),
                ('label_en', models.CharField(max_length=255, verbose_name='Label (English)')),
                ('label_ta', models.CharField(blank=True, max_length=255, null=True, verbose_name='Label (Tamil)')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox (Multiple)'), ('boolean', 'Yes/No (Boolean)')], max_length=50)),
                ('options', models.JSONField(blank=True, help_text='JSON list of options for select/radio/checkbox', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.customformsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
