# Generated by Django 5.2.17 on 2026-08-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customformsection_customformfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRenewalYear',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.AddField(
            model_name='customformfield',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='core.customformfield'),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='depends_on_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='system_name',
            field=models.CharField(blank=True, help_text='Used to map dynamic fields to hardcoded database columns', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('phone', 'Phone Number'), ('nic', 'NIC Number'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox (Multiple)'), ('boolean', 'Yes/No (Boolean)'), ('image', 'Image Upload'), ('autocalc_65', 'Auto Calculate (65th Birthday)')], max_length=50),
        ),
    ]
