# Generated by Django 5.2.17 on 2026-08-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_licenserenewalyear_customformfield_depends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('phone', 'Phone Number'), ('nic', 'NIC Number'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox (Multiple)'), ('boolean', 'Yes/No (Boolean)'), ('image', 'Image Upload'), ('autocalc_65', 'Auto Calculate (65th Birthday)'), ('renewal_history_grid', 'Renewal History (Grid)'), ('current_status_checkboxes', 'Current Status (Checkboxes)')], max_length=50),
        ),
    ]
