# Generated by Django 5.2.17 on 2026-09-17 02:00

from django.db import migrations


def update_labels(apps, schema_editor):
    CustomFormField = apps.get_model('core', 'CustomFormField')
    
    # Update 70th Birthday
    qs_70 = CustomFormField.objects.filter(system_name='sixty_fifth_birthday')
    for f in qs_70:
        f.label_si = 'අවුරුදු 70 සම්පූර්ණ වන දිනය'
        f.label_en = '70th Birthday'
        f.save()

    # Update Outside Area Holder
    qs_outside = CustomFormField.objects.filter(system_name='outside_area_holder')
    for f in qs_outside:
        f.label_si = 'පඬුවස්නුවර නැගෙනහිරින් පිටත පදිංචි, මෙම බලප්‍රදේශය තුළ ඉඩම් හිමි අයෙක්ද?'
        f.label_en = 'Outside Area Holder?'
        f.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customformfield_field_type'),
    ]

    operations = [
        migrations.RunPython(update_labels),
    ]
